openapi: "3.0.2"
info:
  title: express_api
  version: "1.0"
servers:
  - url: http://localhost:3000
paths:
  /users:
    get:
      tags:
        - "user"
      summary: "ユーザー一覧"
      responses:
        "200":
          description: リクエストが成功した時に出るステータスコードです。
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "500":
          $ref: "#/components/responses/500Error"
    post:
      tags:
        - "user"
      summary: "ユーザー作成"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                password:
                  type: string
                money:
                  type: integer
                hp:
                  type: integer
              required:
                - name
                - password
      responses:
        "200":
          description: リクエストが成功した時に出るステータスコードです。
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
        "400":
          $ref: "#/components/responses/400Error"
        "500":
          $ref: "#/components/responses/500Error"

  /users/{user_id}:
    get:
      tags:
        - "user"
      summary: "ユーザー取得"
      parameters:
        - name: user_id
          in: path
          required: true
          description: "ユーザーID"
          schema:
            type: integer
      responses:
        "200":
          description: リクエストが成功した時に出るステータスコードです。
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          $ref: "#/components/responses/400Error"
        "404":
          $ref: "#/components/responses/404Error"
        "500":
          $ref: "#/components/responses/500Error"
    put:
      tags:
        - "user"
      summary: "ユーザー更新"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                password:
                  type: string
                money:
                  type: integer
                hp:
                  type: integer
      responses:
        "200":
          description: リクエストが成功した時に出るステータスコードです。
        "400":
          $ref: "#/components/responses/400Error"
        "404":
          $ref: "#/components/responses/404Error"
        "500":
          $ref: "#/components/responses/500Error"

  /login:
    post:
      tags:
        - "user"
      summary: "ユーザーログイン"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                password:
                  type: string
              required:
                - id
                - password
      responses:
        "200":
          description: リクエストが成功した時に出るステータスコードです。
        "400":
          $ref: "#/components/responses/400Error"
        "401":
          $ref: "#/components/responses/401Error"
        "500":
          $ref: "#/components/responses/500Error"

  /users/buy_item:
    post:
      tags:
        - "user"
      summary: "アイテムを買う"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                item_id:
                  type: integer
                num:
                  type: integer
              required:
                - id
                - item_id
      responses:
        "200":
          description: リクエストが成功した時に出るステータスコードです。
        "400":
          $ref: "#/components/responses/400Error"
        "403":
          $ref: "#/components/responses/403Error"
        "404":
          $ref: "#/components/responses/404Error"
        "405":
          description: |
            リソースの購入後の所持数が上限を超える時に出るステータスコードです。
            ---今回の購入は失敗となります。所持数はそのまま、お金も消費しないです。
          content:
            "application/json":
              schema:
                type: object
                properties:
                  message:
                    title: "エラーメッセージ"
                    type: string
        "500":
          $ref: "#/components/responses/500Error"

  /users/use_item:
    post:
      tags:
        - "user"
      summary: "アイテムを使う"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                item_id:
                  type: integer
                num:
                  type: integer
              required:
                - id
                - item_id
      responses:
        "200":
          description: リクエストが成功した時に出るステータスコードです。
        "400":
          $ref: "#/components/responses/400Error"
        "403":
          $ref: "#/components/responses/403Error"
        "404":
          $ref: "#/components/responses/404Error"
        "500":
          $ref: "#/components/responses/500Error"

  /items:
    get:
      tags:
        - "item"
      summary: "アイテム一覧"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
        "500":
          $ref: "#/components/responses/500Error"
    post:
      tags:
        - "item"
      summary: "アイテム作成"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        "200":
          description: リクエストが成功した時に出るステータスコードです。
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
        "400":
          $ref: "#/components/responses/400Error"
        "500":
          $ref: "#/components/responses/500Error"

  /itmes/{item_id}:
    get:
      tags:
        - "item"
      summary: "アイテム取得"
      parameters:
        - name: item_id
          in: path
          required: true
          description: "アイテムID"
          schema:
            type: integer
      responses:
        "200":
          description: リクエストが成功した時に出るステータスコードです。
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "400":
          $ref: "#/components/responses/400Error"
        "500":
          $ref: "#/components/responses/500Error"
    put:
      tags:
        - "item"
      summary: "アイテム更新"
      parameters:
        - name: item_id
          in: path
          required: true
          description: "アイテムID"
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        "200":
          description: リクエストが成功した時に出るステータスコードです。
        "400":
          $ref: "#/components/responses/400Error"
        "404":
          $ref: "#/components/responses/404Error"
        "500":
          $ref: "#/components/responses/500Error"
    delete:
      tags:
        - "item"
      summary: "アイテム削除"
      parameters:
        - name: item_id
          in: path
          required: true
          description: "アイテムID"
          schema:
            type: integer
      responses:
        "200":
          description: リクエストが成功した時に出るステータスコードです。
        "400":
          $ref: "#/components/responses/400Error"
        "404":
          $ref: "#/components/responses/404Error"
        "500":
          $ref: "#/components/responses/500Error"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1001
        name:
          type: string
          example: "user01"
        money:
          type: integer
          example: 100
        hp:
          type: integer
          example: 100
      required:
        - id
        - name
        - money
        - hp

    Item:
      type: object
      properties:
        id:
          type: integer
          example: 1001
        name:
          type: string
          example: "item01"
        heal:
          type: integer
          example: 10
        price:
          type: integer
          example: 10

  responses:
    404Error:
      description: |
        データが発見できない時に出るステータスコードです。
      content:
        "application/json":
          schema:
            type: object
            properties:
              message:
                title: "エラーメッセージ"
                type: string
    403Error:
      description: |
        リソースが足りない時に出るステータスコードです。
      content:
        "application/json":
          schema:
            type: object
            properties:
              message:
                title: "エラーメッセージ"
                type: string
    401Error:
      description: |
        ユーザー認証が失敗した時に出るステータスコードです。
      content:
        "application/json":
          schema:
            type: object
            properties:
              message:
                title: "エラーメッセージ"
                type: string
    500Error:
      description: |
        サーバー側で処理が失敗した時に出るステータスコードです。
      content:
        "application/json":
          schema:
            type: object
            properties:
              message:
                title: "エラーメッセージ"
                type: string
    400Error:
      description: |
        リクエストのパラメータかボディが違った時に出るステータスコードです。
      content:
        "application/json":
          schema:
            type: object
            properties:
              message:
                title: "エラーメッセージ"
                type: string
